package com.example.dz83month.repository

import com.example.dz83month.CatModel

class CatRepository {
    private var catModelList= mutableListOf<CatModel>()
    fun getListOfCatHTTP(): List<CatModel>{
        catModelList.add(CatModel("https://http.cat/100", "Continue"))
        catModelList.add(CatModel("https://http.cat/101", "Switching Protocols"))
        catModelList.add(CatModel("https://http.cat/102", "Processing"))
        catModelList.add(CatModel("https://http.cat/103", "Early Hints"))
        catModelList.add(CatModel("https://http.cat/200", "OK"))
        catModelList.add(CatModel("https://http.cat/201", "Created"))
        catModelList.add(CatModel("https://http.cat/202", "Accepted"))
        catModelList.add(CatModel("https://http.cat/203", "Non-Authoritative Information"))
        catModelList.add(CatModel("https://http.cat/204", "No Content"))
        catModelList.add(CatModel("https://http.cat/206", "Partial Content"))
        catModelList.add(CatModel("https://http.cat/207", "Multi-Status"))
        catModelList.add(CatModel("https://http.cat/300", "Multiple Choices"))
        catModelList.add(CatModel("https://http.cat/301", "Moved Permanently"))
        catModelList.add(CatModel("https://http.cat/302", "Found"))
        catModelList.add(CatModel("https://http.cat/303", "See Other"))
        catModelList.add(CatModel("https://http.cat/304", "Not Modified"))
        catModelList.add(CatModel("https://http.cat/305", "Use Proxy"))
        catModelList.add(CatModel("https://http.cat/307", "Temporary Redirect"))
        catModelList.add(CatModel("https://http.cat/308", "Permanent Redirect"))
        catModelList.add(CatModel("https://http.cat/400", "Bad Request"))
        catModelList.add(CatModel("https://http.cat/401", "Unauthorized"))
        catModelList.add(CatModel("https://http.cat/402", "Payment Required"))
        catModelList.add(CatModel("https://http.cat/403", "Forbidden"))
        catModelList.add(CatModel("https://http.cat/404", "Not Found"))
        catModelList.add(CatModel("https://http.cat/405", "Method Not Allowed"))
        catModelList.add(CatModel("https://http.cat/406", "Not Acceptable"))
        catModelList.add(CatModel("https://http.cat/407", "Proxy Authentication Required"))
        catModelList.add(CatModel("https://http.cat/408", "Request Timeout"))
        catModelList.add(CatModel("https://http.cat/409", "Conflict"))
        catModelList.add(CatModel("https://http.cat/410", "Gone"))
        catModelList.add(CatModel("https://http.cat/411", "Length Required"))
        catModelList.add(CatModel("https://http.cat/412", "Precondition Failed"))
        catModelList.add(CatModel("https://http.cat/413", "Payload Too Large"))
        catModelList.add(CatModel("https://http.cat/414", "Request-URI Too Long"))
        catModelList.add(CatModel("https://http.cat/415", "Unsupported Media Type"))
        catModelList.add(CatModel("https://http.cat/416", "Request Range Satisfiable"))
        catModelList.add(CatModel("https://http.cat/417", "Expectation Failed"))
        catModelList.add(CatModel("https://http.cat/418", "I'm a teapot"))
        catModelList.add(CatModel("https://http.cat/420", "Enhance Your Calm"))
        catModelList.add(CatModel("https://http.cat/421", "Misdirected Request"))
        catModelList.add(CatModel("https://http.cat/422", "Unprocessable Entity"))
        catModelList.add(CatModel("https://http.cat/423", "Locked"))
        catModelList.add(CatModel("https://http.cat/424", "Failed Dependency"))
        catModelList.add(CatModel("https://http.cat/425", "Too Early"))
        catModelList.add(CatModel("https://http.cat/426", "Upgrade Requested"))
        catModelList.add(CatModel("https://http.cat/429", "Too Many Requested"))
        catModelList.add(CatModel("https://http.cat/431", "Request Header Fields Too Large"))
        catModelList.add(CatModel("https://http.cat/444", "No Response"))
        catModelList.add(CatModel("https://http.cat/450", "Blocked Windows Parental Controls"))
        catModelList.add(CatModel("https://http.cat/451", "Unavailable For Legal Reasons"))
        catModelList.add(CatModel("https://http.cat/497", "HTTP Request Sent HTTPS Port"))
        catModelList.add(CatModel("https://http.cat/498", "Token expired/invalid"))
        catModelList.add(CatModel("https://http.cat/499", "Client Closed Request"))
        catModelList.add(CatModel("https://http.cat/500", "Internal Server Error"))
        catModelList.add(CatModel("https://http.cat/501", "Not Implemented"))
        catModelList.add(CatModel("https://http.cat/502", "Bad Gateway"))
        catModelList.add(CatModel("https://http.cat/503", "Service Unavailable"))
        catModelList.add(CatModel("https://http.cat/504", "Gateway Timeout"))
        catModelList.add(CatModel("https://http.cat/506", "Variant Also Negotiates"))
        catModelList.add(CatModel("https://http.cat/507", "Insuffcient Storage"))
        catModelList.add(CatModel("https://http.cat/508", "Loop Detected"))
        catModelList.add(CatModel("https://http.cat/509", "Bandwidth Limit Exceeded"))
        catModelList.add(CatModel("https://http.cat/510", "Not Extended"))
        catModelList.add(CatModel("https://http.cat/511", "Network Authentication Required"))
        catModelList.add(CatModel("https://http.cat/521", "Web Server Is Down"))
        catModelList.add(CatModel("https://http.cat/522", "Connection Timeout Out"))
        catModelList.add(CatModel("https://http.cat/523", "Origin Is Unreachable"))
        catModelList.add(CatModel("https://http.cat/525", "SSL Handshake Failed"))
        catModelList.add(CatModel("https://http.cat/599", "Network Connect Timeout Error"))
        return catModelList
    }
}